[metadata]
name = indra_perturbseq
version = 0.1.0
description = Using INDRA to explain Perturb-seq data
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD-2-Clause

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    indra @ git+https://github.com/gyorilab/indra.git
    indra_cogex @ git+https://github.com/gyorilab/indra_cogex.git
    networkx
    numpy
    pandas
    matplotlib
    seaborn

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    indra-ps-1hop = indra_perturbseq.pipelines.onehop:main
    indra-ps-2hop = indra_perturbseq.pipelines.twohop:main
    indra-ps-3hop = indra_perturbseq.pipelines.threehop:main
    indra-ps-multihop = indra_perturbseq.pipelines.multihop:main
    indra-ps-permuted = indra_perturbseq.pipelines.permuted:main
    indra-ps-fp-eval = indra_perturbseq.evaluation.false_positives:main
    indra-ps-tpr-fpr = indra_perturbseq.evaluation.tpr_fpr:main
    indra-ps-outliers = indra_perturbseq.evaluation.outliers:main

[flake8]
max-line-length = 99
exclude =
    archive/
    .git
    __pycache__
