[metadata]
name = indra_perturbseq
version = 0.1.0
description = Using INDRA to explain Perturb-seq data
long_description = file: README.md
long_description_content_type = text/markdown
license = BSD-2-Clause

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    indra @ git+https://github.com/gyorilab/indra.git
    indra_cogex @ git+https://github.com/gyorilab/indra_cogex.git
    networkx
    numpy
    pandas
    matplotlib
    seaborn
    scanpy
    tenacity
    omnipath
    plotly

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    indra-ps-1hop = indra_perturbseq.pipelines.onehop:main
    indra-ps-2hop = indra_perturbseq.pipelines.twohop:main
    indra-ps-3hop = indra_perturbseq.pipelines.threehop:main
    indra-ps-4hop = indra_perturbseq.pipelines.fourhop:main
    indra-ps-multihop = indra_perturbseq.pipelines.multihop:main
    indra-ps-permuted = indra_perturbseq.pipelines.permuted:main
    indra-ps-omnipath = indra_perturbseq.pipelines.omnipath:main
    indra-ps-indra-rest = indra_perturbseq.pipelines.indra_rest:main
    indra-ps-fp-eval = indra_perturbseq.evaluation.false_positives:main
    indra-ps-tpr-fpr = indra_perturbseq.evaluation.tpr_fpr:main
    indra-ps-sign-directionality = indra_perturbseq.evaluation.sign_directionality:main
    indra-ps-outliers = indra_perturbseq.evaluation.outliers:main
    indra-ps-bulk-eval = indra_perturbseq.evaluation.bulk_rna_eval:main
    indra-ps-bulk-vs-sc = indra_perturbseq.evaluation.bulk_vs_sc:main
    indra-ps-permuted-compare = indra_perturbseq.evaluation.permuted_comparison:main
    indra-ps-descendants = indra_perturbseq.evaluation.descendants:main
    indra-ps-target-inspect = indra_perturbseq.evaluation.target_inspection:main
    indra-ps-mesh-coverage = indra_perturbseq.evaluation.mesh_coverage:main
    indra-ps-deg = indra_perturbseq.preprocessing.perturbseq_deg:main
    indra-ps-mesh-reference = indra_perturbseq.preprocessing.mesh_reference:main
    indra-ps-c14-mesh = indra_perturbseq.preprocessing.c14_mesh:main
    indra-ps-mesh-annotate = indra_perturbseq.preprocessing.mesh_annotate:main
    indra-ps-gwas = indra_perturbseq.preprocessing.gwas:main
    indra-ps-gene-list = indra_perturbseq.preprocessing.gene_list:main
    indra-ps-bulk-deg = indra_perturbseq.preprocessing.bulk_rna_deg:main
    indra-ps-sc-validation = indra_perturbseq.preprocessing.sc_rna_validation:main
    indra-ps-cell-counts = indra_perturbseq.preprocessing.cell_counts:main
    indra-ps-uniprot-convert = indra_perturbseq.preprocessing.uniprot_convert:main
    indra-ps-permuted-dataset = indra_perturbseq.preprocessing.permuted_dataset:main
    indra-ps-plot-landscape = indra_perturbseq.plotting.landscape:main
    indra-ps-plot-network = indra_perturbseq.plotting.network:main
    indra-ps-plot-pathway-landscape = indra_perturbseq.plotting.pathway_landscape:main
    indra-ps-plot-roc = indra_perturbseq.plotting.roc:main
    indra-ps-plot-boxplots = indra_perturbseq.plotting.boxplots:main
    indra-ps-plot-pval-bins = indra_perturbseq.plotting.pvalue_bins:main
    indra-ps-plot-pval-line = indra_perturbseq.plotting.pvalue_bins:main_pval_line
    indra-ps-plot-lfc-bins = indra_perturbseq.plotting.pvalue_bins:main_lfc
    indra-ps-plot-lfc-line = indra_perturbseq.plotting.pvalue_bins:main_lfc_line
    indra-ps-plot-lfc-binshare-line = indra_perturbseq.plotting.pvalue_bins:main_lfc_binshare_line
    indra-ps-plot-lines = indra_perturbseq.plotting.line_plots:main
    indra-ps-html-assembler = indra_perturbseq.postprocessing.html_assembler:main
    indra-ps-2hop-cleanup = indra_perturbseq.postprocessing.twohop_cleanup:main
    indra-ps-self-targets = indra_perturbseq.postprocessing.self_targets:main
    indra-ps-top-results = indra_perturbseq.postprocessing.top_results:main
    indra-ps-checkpoint = indra_perturbseq.postprocessing.checkpoint:main
    indra-ps-endo-overlap = indra_perturbseq.postprocessing.endothelial_overlap:main
    indra-ps-gwas-filter = indra_perturbseq.postprocessing.gwas_filter:main
    indra-ps-postprocess = indra_perturbseq.postprocessing.postprocess:main

[flake8]
max-line-length = 99
exclude =
    archive/
    .git
    __pycache__
